"""
Utilities package for the Property Maintenance Fines Prediction project.
"""

from .config import (
    PROJECT_ROOT, DATA_DIR, RAW_DATA_DIR, PROCESSED_DATA_DIR, 
    MODEL_DIR, LOG_DIR, TRAIN_FILE, TEST_FILE, ADDRESSES_FILE, 
    LATLONS_FILE, CATEGORICAL_THRESHOLD, UNKNOWN_CATEGORY,
    GRADIENT_BOOSTING_PARAMS, LOGISTIC_REGRESSION_PARAMS,
    CV_FOLDS, SCORING_METRIC, INCONSISTENT_LABELS,
    DATA_LEAKAGE_LABELS, MAILING_ADDRESS_LABELS
)
from .logger import setup_logger, get_logger

__all__ = [
    'PROJECT_ROOT', 'DATA_DIR', 'RAW_DATA_DIR', 'PROCESSED_DATA_DIR',
    'MODEL_DIR', 'LOG_DIR', 'TRAIN_FILE', 'TEST_FILE', 'ADDRESSES_FILE',
    'LATLONS_FILE', 'CATEGORICAL_THRESHOLD', 'UNKNOWN_CATEGORY',
    'GRADIENT_BOOSTING_PARAMS', 'LOGISTIC_REGRESSION_PARAMS',
    'CV_FOLDS', 'SCORING_METRIC', 'INCONSISTENT_LABELS',
    'DATA_LEAKAGE_LABELS', 'MAILING_ADDRESS_LABELS',
    'setup_logger', 'get_logger'
]
